<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.devtest</groupId>
  <artifactId>mvn-ref-test03</artifactId>
  <version>1.0.3-Final</version>
  <packaging>war</packaging>

  <properties>
    <github.packages.url>https://maven.pkg.github.com/normanstrydom/mvn-ref-test03</github.packages.url>
    <mvn-ref-test01.version>1.0.11-Final</mvn-ref-test01.version>
    <mvn-ref-test02.version>1.0.6-Final</mvn-ref-test02.version>
  </properties>

  <scm>
    <connection>scm:git:https://github.com/normanstrydom/mvn-ref-test03.git</connection>
    <developerConnection>scm:git:https://github.com/normanstrydom/mvn-ref-test03.git</developerConnection>
    <url>https://github.com/normanstrydom/mvn-ref-test03</url>
    <tag>mvn-ref-test03-1.0.3-Final</tag>
  </scm>

  <distributionManagement>
    <repository>
      <id>github</id>
      <name>GitHub Packages</name>
      <url>${github.packages.url}</url>
    </repository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.devtest</groupId>
        <artifactId>mvn-ref-test01-bom</artifactId>
        <version>${mvn-ref-test01.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>github</id>
      <name>GitHub Packages</name>
      <url>${github.packages.url}</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>4.0.1</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.devtest</groupId>
      <artifactId>mathfcns</artifactId>
    </dependency>
    <dependency>
      <groupId>com.devtest</groupId>
      <artifactId>stringfcns</artifactId>
    </dependency>
    <dependency>
      <groupId>com.devtest</groupId>
      <artifactId>mvn-ref-test02</artifactId>
      <version>${mvn-ref-test02.version}</version>
    </dependency>
  </dependencies>

</project>